names = ["Chloe", "Anna", "Emma","Kyle"]
print("Come at my house for dinner,", names[0])
print("Come at my house for dinner,", names[1])
print("Come at my house for dinner,", names[2])
print("Come at my house for dinner,", names[3])
print(names[3],"is busy")
names.insert(3, "Robert")
print("Come at my house for dinner,", names[0])
print("Come at my house for dinner,", names[1])
print("Come at my house for dinner,", names[2])
print("Come at my house for dinner,", names[3])

print("\nSorry, we can only invite two people to dinner.")
print("Sorry the table is full,", names[0])
print("Sorry the table is full,", names[1])
print("Come at my house for dinner,", names[2])
print("Come at my house for dinner,", names[3])
del(names[0])
del(names[0])

